name: keyvault fetach secrets

on:
  push:
    branches:
    - main

#env:
 # SECRETVALUE: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}           # Strong box key you generated in the first step
    - uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "keyvaultstaticapp001"
        secrets: 'REGISTRY-PASSWORD, REGISTRY-USERNAME' 
      id: keyvaultaction

    - uses: azure/docker-login@v1
      with:
        login-server: devlopmentacr.azurecr.io
        username: ${{ steps.keyvaultaction.outputs.REGISTRY-USERNAME }}
        password: ${{ steps.keyvaultaction.outputs.REGISTRY-PASSWORD }}
    - run: |
        shell: bash
        working-directory: dockercontent
        docker build . -t devlopmentacr.azurecr.io/dockerwebsite:${{ github.sha }} 
        docker push devlopmentacr.azurecr.io/dockerwebsite:${{ github.sha }} 
