name: keyvault fetach secrets

on:
  push:
    branches:
    - main

env:
 SECRETVALUE: ''
 ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dockercontent
    
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}           # Strong box key you generated in the first step
    - uses: Azure/get-keyvault-secrets@v1.0
      #ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        keyvault: "keyvaultstaticapp001"
        secrets: 'REGISTRY-PASSWORD, REGISTRY-USERNAME' 
      id: keyvaultaction

    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: devlopmentacr.azurecr.io
        username: ${{ steps.keyvaultaction.outputs.REGISTRY-USERNAME }}
        password: ${{ steps.keyvaultaction.outputs.REGISTRY-PASSWORD }}

    - run: |  
       docker build . -t devlopmentacr.azurecr.io/wesitehtml1:${{ github.sha }} 
       docker push devlopmentacr.azurecr.io/websitehtml1:${{ github.sha }} 
